### ISSUE TITLE
build command from documentation not generating relay executable

### ISSUE THREAD

**Issue by sehraramiz** [bepass-org/bepass-relay#14]
i tried to build the relay on my server based on the instructions, but no executable was created after build. according to ```go help build```:
>When the command line specifies a single main package,
build writes the resulting executable to output.
Otherwise build compiles the packages but discards the results,
serving only as a check that the packages can be built.

i used ```-o relay``` flag to fix my problem.
if this is the case please update the docs so other non-go developers like myself can setup relay servers with less struggle.
thank you

**Comment by DanielcoderX** [comment]
Hi there! Thank you so much for your report. We appreciate it! We'll get started on fixing the document right away. Thanks again for your help!
